services:
  postgres:
    image: postgres:16.3-alpine3.20
    container_name: nest-demo
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: nest-demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data: